import { Link } from 'react-router-dom'
import { Footer } from '@/components/Footer'

export function TermsOfService() {
  return (
    <div className="min-h-screen flex flex-col">
      <main className="flex-1 max-w-3xl mx-auto px-4 py-8">
        <Link to="/" className="text-sm text-muted-foreground hover:text-foreground underline">
          &larr; Back to Calculator
        </Link>
        <h1 className="text-2xl font-bold mt-4 mb-2">Terms of Service</h1>
        <p className="text-sm text-muted-foreground mb-8">Last updated: March 21, 2026</p>

        <div className="space-y-6 text-sm leading-relaxed">
          <p>
            Welcome to HomeDecision. Please read these Terms of Service (&quot;Terms&quot;) carefully before using our website and financial analysis tool.
          </p>
          <p>
            By using HomeDecision, you agree to these Terms. If you do not agree, do not use the tool.
          </p>

          <section>
            <h2 className="text-lg font-semibold mt-8 mb-3">1. What HomeDecision Is</h2>
            <p>
              HomeDecision is a free, interactive financial modeling tool. It helps homeowners explore the financial implications of selling their current home versus keeping it as a rental property when relocating.
            </p>
            <p className="mt-3">
              The tool generates projections based on the information you provide and a set of financial assumptions. It is designed to help you think through a complex decision — not to make the decision for you.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mt-8 mb-3">2. What HomeDecision Is Not</h2>
            <p>
              <strong>HomeDecision is not financial advice.</strong> The tool does not provide personalized financial, tax, legal, investment, or real estate advice. No fiduciary relationship is created between you and HomeDecision by your use of this tool.
            </p>
            <p className="mt-3">
              <strong>HomeDecision is not a substitute for professional guidance.</strong> The projections generated by this tool are estimates based on simplified models. They do not account for every variable that affects your financial situation. Before making any financial decision based on information from this tool, consult with:
            </p>
            <ul className="list-disc pl-5 space-y-1 text-sm mt-2">
              <li>A <strong>Certified Public Accountant (CPA)</strong> for tax implications specific to your situation</li>
              <li>A <strong>licensed financial advisor</strong> for investment and retirement planning decisions</li>
              <li>A <strong>mortgage lender</strong> for actual loan qualification, rates, and terms</li>
              <li>A <strong>real estate attorney</strong> for legal matters related to property transactions</li>
              <li>A <strong>licensed insurance professional</strong> for coverage requirements and pricing</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold mt-8 mb-3">3. No Guarantee of Accuracy</h2>
            <p>
              All projections, calculations, and estimates are <strong>approximations based on the inputs you provide and the assumptions built into our models.</strong> Actual financial outcomes will differ — sometimes significantly — from our projections.
            </p>
            <p className="mt-3">Specifically:</p>
            <ul className="list-disc pl-5 space-y-1 text-sm mt-2">
              <li><strong>Tax calculations</strong> use simplified models based on 2024 IRS schedules. They do not account for all deductions, credits, AMT, state-specific rules, or future tax law changes. Your actual tax liability may be materially different.</li>
              <li><strong>Home value projections</strong> assume a steady annual appreciation rate. Real estate markets are volatile. Home values can decline substantially, as occurred in many US markets during 2008-2011.</li>
              <li><strong>Rental income projections</strong> assume consistent occupancy at the rent amount you specify. Actual rental income depends on local market conditions, tenant quality, property condition, and economic factors outside your control.</li>
              <li><strong>Mortgage qualification estimates</strong> (including debt-to-income ratios) are not pre-approvals. Lenders use their own underwriting criteria, which may differ materially from our estimates.</li>
              <li><strong>Retirement account projections</strong> assume a steady annual return rate. Actual investment returns vary year to year and may be negative.</li>
            </ul>
            <p className="mt-3">
              We make reasonable efforts to ensure our calculations are mathematically correct, but we do not warrant that the tool is free from errors.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mt-8 mb-3">4. Your Responsibilities</h2>
            <p>When using HomeDecision, you agree that:</p>
            <ul className="list-disc pl-5 space-y-1 text-sm mt-2">
              <li>You will not rely solely on this tool&apos;s output to make financial decisions</li>
              <li>You understand that all projections are estimates, not guarantees</li>
              <li>You are responsible for verifying all assumptions and inputs</li>
              <li>You will seek professional advice appropriate to your situation before acting on any information provided by this tool</li>
              <li>The information you enter is for your own analysis; you will not enter another person&apos;s financial information without their consent</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold mt-8 mb-3">5. How Your Data Is Handled</h2>
            <p>
              HomeDecision processes all calculations in your web browser. Your financial information is <strong>not transmitted to our servers.</strong>
            </p>
            <ul className="list-disc pl-5 space-y-1 text-sm mt-2">
              <li>Your inputs are saved in your browser&apos;s local storage so you can return to your analysis later</li>
              <li>No account creation is required</li>
              <li>No personal data is collected, stored, or shared by us</li>
              <li>Clearing your browser data will remove your saved inputs</li>
            </ul>
            <p className="mt-3">
              For full details, see our <Link to="/privacy" className="underline hover:text-foreground">Privacy Policy</Link>.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mt-8 mb-3">6. Intellectual Property</h2>
            <p>
              All content, design, code, calculations, and text on HomeDecision are owned by HomeDecision or its licensors. You may use the tool for personal, non-commercial analysis. You may not:
            </p>
            <ul className="list-disc pl-5 space-y-1 text-sm mt-2">
              <li>Copy, modify, or redistribute the tool or its code without permission</li>
              <li>Use the tool to create a competing product or service</li>
              <li>Remove or alter any disclaimers, attributions, or legal notices</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold mt-8 mb-3">7. Limitation of Liability</h2>
            <p>
              <strong>To the fullest extent permitted by law, HomeDecision and its creators, contributors, and affiliates shall not be liable for any direct, indirect, incidental, consequential, or special damages arising from your use of this tool.</strong> This includes, without limitation:
            </p>
            <ul className="list-disc pl-5 space-y-1 text-sm mt-2">
              <li>Financial losses resulting from decisions made using this tool&apos;s projections</li>
              <li>Tax penalties, interest, or additional tax liability not anticipated by the tool</li>
              <li>Mortgage application denials or unfavorable lending terms</li>
              <li>Rental property losses, vacancy, maintenance costs, or tenant issues</li>
              <li>Investment losses or missed investment opportunities</li>
              <li>Any other financial outcome that differs from the tool&apos;s projections</li>
            </ul>
            <p className="mt-3">
              <strong>You use this tool at your own risk.</strong> The projections are educational estimates, not promises of future performance.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mt-8 mb-3">8. Indemnification</h2>
            <p>
              You agree to indemnify and hold harmless HomeDecision and its creators from any claims, damages, losses, or expenses (including reasonable attorney&apos;s fees) arising from your use of the tool, your reliance on its projections, or your violation of these Terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mt-8 mb-3">9. Third-Party Links and Services</h2>
            <p>
              HomeDecision may contain links to third-party websites or services. We do not control, endorse, or assume responsibility for any third-party content, products, or services. Your use of third-party services is governed by their own terms and policies.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mt-8 mb-3">10. Changes to These Terms</h2>
            <p>
              We may update these Terms from time to time. The &quot;Last Updated&quot; date at the top indicates the most recent revision. Continued use of the tool after changes constitutes acceptance of the revised Terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mt-8 mb-3">11. Governing Law</h2>
            <p>
              These Terms are governed by the laws of the State of Texas, without regard to conflict of law principles. Any disputes arising from these Terms or your use of the tool shall be resolved in the courts located in Travis County, Texas.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mt-8 mb-3">12. Severability</h2>
            <p>
              If any provision of these Terms is found to be unenforceable, the remaining provisions will continue in full force and effect.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mt-8 mb-3">13. Entire Agreement</h2>
            <p>
              These Terms, together with our Privacy Policy and Disclaimer, constitute the entire agreement between you and HomeDecision regarding your use of the tool.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mt-8 mb-3">Contact</h2>
            <p>
              If you have questions about these Terms, contact us at: <strong>contact@homedecision.app</strong>
            </p>
          </section>
        </div>
      </main>
      <Footer />
    </div>
  )
}
